server:
  port: 8080

spring:
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 100MB
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/Kaskade
    username: root
    password: Mba230721
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      table-underline: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

file:
  path: /Users/23Fall/JAVA/upload/

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql